--
-- PostgreSQL database dump
--

-- Dumped from database version 14.9
-- Dumped by pg_dump version 14.9

-- Started on 2023-11-05 15:16:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3725 (class 1262 OID 75712)
-- Name: system_ogloszeniowy_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE system_ogloszeniowy_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Polish_Poland.1250';


ALTER DATABASE system_ogloszeniowy_db OWNER TO postgres;

\connect system_ogloszeniowy_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 75769)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_id bigint,
    first_name character varying(255),
    last_name character varying(255),
    birth_date date,
    phone_number character varying(20),
    address_id bigint,
    profile_picture_source character varying(255),
    current_job character varying(3000),
    career_summary character varying(3000),
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- TOC entry 3726 (class 0 OID 0)
-- Dependencies: 216
-- Name: COLUMN accounts.current_job; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.accounts.current_job IS 'Aktualne stanowisko pracy + krótki opis zajmowanego stanowiska';


--
-- TOC entry 3727 (class 0 OID 0)
-- Dependencies: 216
-- Name: COLUMN accounts.career_summary; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.accounts.career_summary IS 'Krótki opis ogólnego doświadczenia zawodowego';


--
-- TOC entry 215 (class 1259 OID 75768)
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 75747)
-- Name: addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    city character varying(255),
    postal_name character varying(255),
    postal_code character varying(10),
    street character varying(255),
    street_number character varying(10),
    apartment_number character varying(10),
    country character varying(10),
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.addresses OWNER TO postgres;

--
-- TOC entry 3728 (class 0 OID 0)
-- Dependencies: 214
-- Name: COLUMN addresses.country; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.addresses.country IS 'Skrót, np. PL, DE';


--
-- TOC entry 213 (class 1259 OID 75746)
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 76257)
-- Name: advertisement_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advertisement_categories (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    advertisement_id bigint NOT NULL,
    parent_advertisement_category_id bigint,
    name character varying(50) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.advertisement_categories OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 76256)
-- Name: advertisement_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advertisement_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advertisement_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 76337)
-- Name: advertisement_opportunities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advertisement_opportunities (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    advertisement_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.advertisement_opportunities OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 76336)
-- Name: advertisement_opportunities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advertisement_opportunities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advertisement_opportunities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 76312)
-- Name: advertisement_requirements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advertisement_requirements (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    advertisement_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.advertisement_requirements OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 76311)
-- Name: advertisement_requirements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advertisement_requirements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advertisement_requirements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 76287)
-- Name: advertisement_responsibilities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advertisement_responsibilities (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    advertisement_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.advertisement_responsibilities OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 76286)
-- Name: advertisement_responsibilities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advertisement_responsibilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advertisement_responsibilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 76212)
-- Name: advertisements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advertisements (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    company_id bigint NOT NULL,
    "position" character varying(100) NOT NULL,
    position_level_id bigint NOT NULL,
    contract_type_id bigint NOT NULL,
    working_time_type_id bigint NOT NULL,
    job_type_id bigint NOT NULL,
    salary_from integer NOT NULL,
    salary_to integer NOT NULL,
    working_days character varying(100),
    working_hours character varying(100),
    expiration_date date NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.advertisements OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 76211)
-- Name: advertisements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advertisements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advertisements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 76105)
-- Name: companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    iframe_hyperlink character varying(511),
    address_id bigint NOT NULL,
    description character varying(255),
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.companies OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 76104)
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 76132)
-- Name: contract_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contract_types (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(50) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.contract_types OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 76131)
-- Name: contract_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contract_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 75718)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 75713)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 75926)
-- Name: education_levels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.education_levels (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.education_levels OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 75925)
-- Name: education_levels_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.education_levels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.education_levels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 76192)
-- Name: job_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_types (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.job_types OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 76191)
-- Name: job_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 75978)
-- Name: language_levels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.language_levels (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.language_levels OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 75977)
-- Name: language_levels_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.language_levels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.language_levels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 76152)
-- Name: position_levels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.position_levels (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(50) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.position_levels OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 76151)
-- Name: position_levels_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.position_levels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.position_levels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 75801)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(30) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 75800)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 76053)
-- Name: user_certificates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_certificates (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_id bigint,
    name character varying(255) NOT NULL,
    host character varying(100) NOT NULL,
    date date NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.user_certificates OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 76052)
-- Name: user_certificates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_certificates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 75946)
-- Name: user_education; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_education (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_id bigint,
    school_name character varying(255) NOT NULL,
    school_location character varying(100) NOT NULL,
    education_level_id bigint NOT NULL,
    specialization character varying(100),
    period_start date NOT NULL,
    period_end date,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.user_education OWNER TO postgres;

--
-- TOC entry 3730 (class 0 OID 0)
-- Dependencies: 232
-- Name: COLUMN user_education.period_end; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.user_education.period_end IS 'null oznacza, że nadal w tej szkole';


--
-- TOC entry 231 (class 1259 OID 75945)
-- Name: user_education_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_education ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 75876)
-- Name: user_experiences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_experiences (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_id bigint,
    "position" character varying(100) NOT NULL,
    company_name character varying(100) NOT NULL,
    location character varying(100) NOT NULL,
    period_start date NOT NULL,
    period_end date,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.user_experiences OWNER TO postgres;

--
-- TOC entry 3731 (class 0 OID 0)
-- Dependencies: 226
-- Name: COLUMN user_experiences.period_end; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.user_experiences.period_end IS 'null oznacza, że nadal w tej pracy';


--
-- TOC entry 228 (class 1259 OID 75901)
-- Name: user_experiences_duties; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_experiences_duties (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_experience_id bigint,
    duty character varying(100) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.user_experiences_duties OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 75900)
-- Name: user_experiences_duties_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_experiences_duties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_experiences_duties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 75875)
-- Name: user_experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 75998)
-- Name: user_languages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_languages (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_id bigint,
    language character varying(100) NOT NULL,
    language_level_id bigint NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.user_languages OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 75997)
-- Name: user_languages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 76078)
-- Name: user_links; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_links (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_id bigint,
    name character varying(50) NOT NULL,
    hyperlink character varying(511) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.user_links OWNER TO postgres;

--
-- TOC entry 3732 (class 0 OID 0)
-- Dependencies: 242
-- Name: COLUMN user_links.name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.user_links.name IS 'Nazwa strony/portalu, np. Linked.in, GitHub itp.';


--
-- TOC entry 241 (class 1259 OID 76077)
-- Name: user_links_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 76028)
-- Name: user_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_skills (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    user_id bigint,
    skill_name character varying(100) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.user_skills OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 76027)
-- Name: user_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 75724)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    enabled boolean NOT NULL,
    username character varying(255),
    password_hash character(60),
    account_non_expired boolean DEFAULT true NOT NULL,
    account_non_locked boolean DEFAULT true NOT NULL,
    credentials_non_expired boolean DEFAULT true NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 3733 (class 0 OID 0)
-- Dependencies: 212
-- Name: COLUMN users.password_hash; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.users.password_hash IS 'bcrypt';


--
-- TOC entry 222 (class 1259 OID 75850)
-- Name: users_actions_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_actions_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    key character varying(255) NOT NULL,
    created_date timestamp with time zone,
    action smallint DEFAULT 0 NOT NULL
);


ALTER TABLE public.users_actions_tokens OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 75863)
-- Name: users_actions_tokens_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_actions_tokens_history (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    key character varying(255) NOT NULL,
    created_date timestamp with time zone,
    action smallint DEFAULT 0 NOT NULL,
    used_date timestamp with time zone,
    deleted_date timestamp with time zone
);


ALTER TABLE public.users_actions_tokens_history OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 75862)
-- Name: users_actions_tokens_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_actions_tokens_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_actions_tokens_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 75849)
-- Name: users_actions_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_actions_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_actions_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 75723)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 75824)
-- Name: users_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_roles (
    id bigint NOT NULL,
    user_id bigint,
    role_id bigint,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint
);


ALTER TABLE public.users_roles OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 75823)
-- Name: users_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 76172)
-- Name: working_time_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.working_time_types (
    id bigint NOT NULL,
    uuid character varying(36) NOT NULL,
    name character varying(50) NOT NULL,
    created_date timestamp with time zone,
    user_id_created bigint,
    last_modified_date timestamp with time zone,
    user_id_last_modified bigint,
    status smallint NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.working_time_types OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 76171)
-- Name: working_time_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.working_time_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.working_time_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3673 (class 0 OID 75769)
-- Dependencies: 216
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, uuid, user_id, first_name, last_name, birth_date, phone_number, address_id, profile_picture_source, current_job, career_summary, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
1	1ce94986-e134-4bca-a690-fce62832af17	2	Damian	Raczek	\N	\N	\N	\N	\N	\N	\N	1	\N	1	1	0
2	7f25baec-fd32-4737-81dd-fd04c496f410	3	Damian	Raczek	\N	\N	\N	\N	\N	\N	\N	1	\N	1	1	0
\.


--
-- TOC entry 3671 (class 0 OID 75747)
-- Dependencies: 214
-- Data for Name: addresses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.addresses (id, uuid, city, postal_name, postal_code, street, street_number, apartment_number, country, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3713 (class 0 OID 76257)
-- Dependencies: 256
-- Data for Name: advertisement_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advertisement_categories (id, uuid, advertisement_id, parent_advertisement_category_id, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3719 (class 0 OID 76337)
-- Dependencies: 262
-- Data for Name: advertisement_opportunities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advertisement_opportunities (id, uuid, advertisement_id, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3717 (class 0 OID 76312)
-- Dependencies: 260
-- Data for Name: advertisement_requirements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advertisement_requirements (id, uuid, advertisement_id, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3715 (class 0 OID 76287)
-- Dependencies: 258
-- Data for Name: advertisement_responsibilities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advertisement_responsibilities (id, uuid, advertisement_id, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3711 (class 0 OID 76212)
-- Dependencies: 254
-- Data for Name: advertisements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advertisements (id, uuid, company_id, "position", position_level_id, contract_type_id, working_time_type_id, job_type_id, salary_from, salary_to, working_days, working_hours, expiration_date, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3701 (class 0 OID 76105)
-- Dependencies: 244
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.companies (id, uuid, name, iframe_hyperlink, address_id, description, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3703 (class 0 OID 76132)
-- Dependencies: 246
-- Data for Name: contract_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contract_types (id, uuid, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3667 (class 0 OID 75718)
-- Dependencies: 210
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
20102023-init_sql	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.205855	1	EXECUTED	8:ade4f5519a4a169e8b483cd44ae6ab40	createProcedure procedureName=initialize_sql		\N	4.8.0	\N	\N	9192719861
20102023-create_table_users	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.270452	2	EXECUTED	8:0c0f5146a0fcd8bdb6075fc83c0b27bf	createTable tableName=users; createIndex indexName=users_uuid_idx, tableName=users		\N	4.8.0	\N	\N	9192719861
20102023-create_table_addresses	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.32863	3	EXECUTED	8:21277dcf57f3be32960b986df1bd614a	createTable tableName=addresses; createIndex indexName=addresses_uuid_idx, tableName=addresses		\N	4.8.0	\N	\N	9192719861
20102023-create_table_accounts	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.40005	4	EXECUTED	8:c25a3274af215ae7565fedc10a5b583b	createTable tableName=accounts; createIndex indexName=accounts_uuid_idx, tableName=accounts		\N	4.8.0	\N	\N	9192719861
20102023-create_table_roles	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.480375	5	EXECUTED	8:7550e5069d354de73092ac1e66d202f1	createTable tableName=roles; createIndex indexName=roles_name_idx, tableName=roles; createIndex indexName=roles_uuid_idx, tableName=roles		\N	4.8.0	\N	\N	9192719861
20102023-create_table_users_roles	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.50794	6	EXECUTED	8:bf3ac3aed8b482a3e70293adce7748e8	createTable tableName=users_roles		\N	4.8.0	\N	\N	9192719861
20102023-create_table_users_actions_tokens	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.541091	7	EXECUTED	8:ed687b6e601665fcbb30f69d39882420	createTable tableName=users_actions_tokens; createIndex indexName=users_actions_tokens_token_key_idx, tableName=users_actions_tokens		\N	4.8.0	\N	\N	9192719861
create_table_users_actions_tokens_history	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.564298	8	EXECUTED	8:bea3c907600387447a57c8951135ddcf	createTable tableName=users_actions_tokens_history		\N	4.8.0	\N	\N	9192719861
20102023-grant_authorities_and_create_uidx	Damian Raczek	db/changelog/2023/10/20-10-2023-changelog.xml	2023-11-05 14:58:40.598186	9	EXECUTED	8:5790cf8fd31bd63981fdc560fd98c368	sql		\N	4.8.0	\N	\N	9192719861
04112023-create_table_user_experiences	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:40.65353	10	EXECUTED	8:30d4bf3ea8089041cabaac9b572992cf	createTable tableName=user_experiences; createIndex indexName=user_experiences_uuid_idx, tableName=user_experiences		\N	4.8.0	\N	\N	9192719861
04112023-create_table_user_experiences_duties	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:40.701881	11	EXECUTED	8:aba1cb66bf4ef07b1bdc39a4b3a4545b	createTable tableName=user_experiences_duties; createIndex indexName=user_experiences_duties_uuid_idx, tableName=user_experiences_duties		\N	4.8.0	\N	\N	9192719861
04112023-create_table_education_levels	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:40.746018	12	EXECUTED	8:418e1840503cd6d335d07036eb989f1f	createTable tableName=education_levels; createIndex indexName=education_levels_uuid_idx, tableName=education_levels		\N	4.8.0	\N	\N	9192719861
04112023-create_table_user_education	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:40.806295	13	EXECUTED	8:b2ef2ffb5bc7279dc28e2ec02143bf41	createTable tableName=user_education; createIndex indexName=user_education_uuid_idx, tableName=user_education		\N	4.8.0	\N	\N	9192719861
04112023-create_table_language_levels	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:40.863083	14	EXECUTED	8:dd729d190cd6ee49d83b4aefd10eb941	createTable tableName=language_levels; createIndex indexName=language_levels_uuid_idx, tableName=language_levels		\N	4.8.0	\N	\N	9192719861
04112023-create_table_user_languages	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:40.92212	15	EXECUTED	8:9ea08e12f12cb79494d090f062dc69ef	createTable tableName=user_languages; createIndex indexName=user_languages_uuid_idx, tableName=user_languages		\N	4.8.0	\N	\N	9192719861
04112023-create_table_user_skills	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:40.968914	16	EXECUTED	8:80ba266bae4fdc863defbb3c9d213c6f	createTable tableName=user_skills; createIndex indexName=user_skills_uuid_idx, tableName=user_skills		\N	4.8.0	\N	\N	9192719861
04112023-create_table_user_certificates	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.016476	17	EXECUTED	8:ccde7f5b0f0fd2e31e2fbb83a2093981	createTable tableName=user_certificates; createIndex indexName=user_certificates_uuid_idx, tableName=user_certificates		\N	4.8.0	\N	\N	9192719861
04112023-create_table_user_links	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.094352	18	EXECUTED	8:9fd0d301d3a6c63d4bb1de0bc63dfc9a	createTable tableName=user_links; createIndex indexName=user_links_uuid_idx, tableName=user_links		\N	4.8.0	\N	\N	9192719861
04112023-create_table_companies	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.174074	19	EXECUTED	8:7fbfe7616dec5a34a7fb13c875580bca	createTable tableName=companies; createIndex indexName=companies_uuid_idx, tableName=companies		\N	4.8.0	\N	\N	9192719861
04112023-create_table_contract_types	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.232518	20	EXECUTED	8:d245e14182770e4dcf8213c3f1728e99	createTable tableName=contract_types; createIndex indexName=contract_types_uuid_idx, tableName=contract_types		\N	4.8.0	\N	\N	9192719861
04112023-create_table_position_levels	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.296727	21	EXECUTED	8:2e3d237955611ec37a2928fcce843b03	createTable tableName=position_levels; createIndex indexName=position_levels_uuid_idx, tableName=position_levels		\N	4.8.0	\N	\N	9192719861
04112023-create_table_working_time_types	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.359648	22	EXECUTED	8:641d1d8aefa198305d2abf71fba34cc2	createTable tableName=working_time_types; createIndex indexName=working_time_types_uuid_idx, tableName=working_time_types		\N	4.8.0	\N	\N	9192719861
04112023-create_table_job_types	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.41748	23	EXECUTED	8:c9af716271668d6047202c0b30afc05b	createTable tableName=job_types; createIndex indexName=job_types_uuid_idx, tableName=job_types		\N	4.8.0	\N	\N	9192719861
04112023-create_table_advertisements	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.484915	24	EXECUTED	8:8d5a99cbd15f2dcb30a4fd7161e44e75	createTable tableName=advertisements; createIndex indexName=advertisements_uuid_idx, tableName=advertisements		\N	4.8.0	\N	\N	9192719861
04112023-create_table_advertisement_categories	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.546865	25	EXECUTED	8:0c06fbf8720928773c5936d4da8c92d2	createTable tableName=advertisement_categories; createIndex indexName=advertisement_categories_uuid_idx, tableName=advertisement_categories		\N	4.8.0	\N	\N	9192719861
04112023-create_table_advertisement_responsibilities	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.594707	26	EXECUTED	8:270a9d96e625fbae6eb9a892354a18c6	createTable tableName=advertisement_responsibilities; createIndex indexName=advertisement_responsibilities_uuid_idx, tableName=advertisement_responsibilities		\N	4.8.0	\N	\N	9192719861
04112023-create_table_advertisement_requirements	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.646603	27	EXECUTED	8:06d924edf23e4da726c4be52cee3c40e	createTable tableName=advertisement_requirements; createIndex indexName=advertisement_requirements_uuid_idx, tableName=advertisement_requirements		\N	4.8.0	\N	\N	9192719861
04112023-create_table_advertisement_opportunities	Damian Raczek	db/changelog/2023/11/04-11-2023-changelog.xml	2023-11-05 14:58:41.694104	28	EXECUTED	8:0802d73d03e3251dccfc98afd32296c8	createTable tableName=advertisement_opportunities; createIndex indexName=advertisement_opportunities_uuid_idx, tableName=advertisement_opportunities		\N	4.8.0	\N	\N	9192719861
20231020-import-data	draczek	db/changelog/data/2023/10/20-10-changelog.xml	2023-11-05 14:58:41.968645	29	EXECUTED	8:a1088c0c1354d04fd63fedd00d8ef9f3	loadData tableName=users; loadData tableName=users; sql; loadData tableName=accounts; sql; loadData tableName=roles; sql; loadData tableName=users_roles; sql		\N	4.8.0	\N	\N	9192719861
\.


--
-- TOC entry 3666 (class 0 OID 75713)
-- Dependencies: 209
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- TOC entry 3687 (class 0 OID 75926)
-- Dependencies: 230
-- Data for Name: education_levels; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.education_levels (id, uuid, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3709 (class 0 OID 76192)
-- Dependencies: 252
-- Data for Name: job_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_types (id, uuid, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3691 (class 0 OID 75978)
-- Dependencies: 234
-- Data for Name: language_levels; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.language_levels (id, uuid, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3705 (class 0 OID 76152)
-- Dependencies: 248
-- Data for Name: position_levels; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.position_levels (id, uuid, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3675 (class 0 OID 75801)
-- Dependencies: 218
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, uuid, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
1	027357a8-f784-4c4b-96c4-475481dc5df2	ROLE_SUPER_ADMIN	2022-11-29 12:00:00+01	1	2022-11-29 12:00:00+01	1	1	0
2	c0dc4f98-9563-4fe3-b959-8ef4509893af	ROLE_ADMIN	2022-11-29 12:00:00+01	1	2022-11-29 12:00:00+01	1	1	0
3	2b109fa4-3467-4133-ae63-cb8580083e4c	ROLE_USER	2022-11-29 12:00:00+01	1	2022-11-29 12:00:00+01	1	1	0
\.


--
-- TOC entry 3697 (class 0 OID 76053)
-- Dependencies: 240
-- Data for Name: user_certificates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_certificates (id, uuid, user_id, name, host, date, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3689 (class 0 OID 75946)
-- Dependencies: 232
-- Data for Name: user_education; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_education (id, uuid, user_id, school_name, school_location, education_level_id, specialization, period_start, period_end, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3683 (class 0 OID 75876)
-- Dependencies: 226
-- Data for Name: user_experiences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_experiences (id, uuid, user_id, "position", company_name, location, period_start, period_end, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3685 (class 0 OID 75901)
-- Dependencies: 228
-- Data for Name: user_experiences_duties; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_experiences_duties (id, uuid, user_experience_id, duty, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3693 (class 0 OID 75998)
-- Dependencies: 236
-- Data for Name: user_languages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_languages (id, uuid, user_id, language, language_level_id, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3699 (class 0 OID 76078)
-- Dependencies: 242
-- Data for Name: user_links; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_links (id, uuid, user_id, name, hyperlink, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3695 (class 0 OID 76028)
-- Dependencies: 238
-- Data for Name: user_skills; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_skills (id, uuid, user_id, skill_name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3669 (class 0 OID 75724)
-- Dependencies: 212
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, uuid, enabled, username, password_hash, account_non_expired, account_non_locked, credentials_non_expired, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
1	00000000-0000-0000-0000-000000000001	t	SYSTEM	\N	t	t	t	1970-01-01 00:00:00+01	1	1970-01-01 00:00:00+01	1	1	0
2	f1273d55-14da-4c3e-b74e-d1ffb181538d	t	draczekprojekt@gmail.com	$2a$10$N3UYqAblcf7of/3BNnCtauEydheifdLDbkSqxcsxcmD8PNpoKKHjC	t	t	t	2022-11-29 00:00:00+01	1	2022-11-29 00:00:00+01	1	1	0
3	f6fe6282-cb3c-4289-9c1d-b879be9479cc	t	godzina.wychowawcza12@gmail.com	$2a$10$N3UYqAblcf7of/3BNnCtauEydheifdLDbkSqxcsxcmD8PNpoKKHjC	t	t	t	2022-11-29 00:00:00+01	1	2022-11-29 00:00:00+01	1	1	0
\.


--
-- TOC entry 3679 (class 0 OID 75850)
-- Dependencies: 222
-- Data for Name: users_actions_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_actions_tokens (id, user_id, key, created_date, action) FROM stdin;
\.


--
-- TOC entry 3681 (class 0 OID 75863)
-- Dependencies: 224
-- Data for Name: users_actions_tokens_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_actions_tokens_history (id, user_id, key, created_date, action, used_date, deleted_date) FROM stdin;
\.


--
-- TOC entry 3677 (class 0 OID 75824)
-- Dependencies: 220
-- Data for Name: users_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_roles (id, user_id, role_id, created_date, user_id_created, last_modified_date, user_id_last_modified) FROM stdin;
1	2	1	2022-11-29 12:00:00+01	1	2022-11-29 12:00:00+01	1
2	2	2	2022-11-29 12:00:00+01	1	2022-11-29 12:00:00+01	1
3	2	3	2022-11-29 12:00:00+01	1	2022-11-29 12:00:00+01	1
4	3	3	2022-11-29 12:00:00+01	1	2022-11-29 12:00:00+01	1
\.


--
-- TOC entry 3707 (class 0 OID 76172)
-- Dependencies: 250
-- Data for Name: working_time_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.working_time_types (id, uuid, name, created_date, user_id_created, last_modified_date, user_id_last_modified, status, version) FROM stdin;
\.


--
-- TOC entry 3738 (class 0 OID 0)
-- Dependencies: 215
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_seq', 3, false);


--
-- TOC entry 3739 (class 0 OID 0)
-- Dependencies: 213
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.addresses_id_seq', 1, false);


--
-- TOC entry 3740 (class 0 OID 0)
-- Dependencies: 255
-- Name: advertisement_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advertisement_categories_id_seq', 1, false);


--
-- TOC entry 3741 (class 0 OID 0)
-- Dependencies: 261
-- Name: advertisement_opportunities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advertisement_opportunities_id_seq', 1, false);


--
-- TOC entry 3742 (class 0 OID 0)
-- Dependencies: 259
-- Name: advertisement_requirements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advertisement_requirements_id_seq', 1, false);


--
-- TOC entry 3743 (class 0 OID 0)
-- Dependencies: 257
-- Name: advertisement_responsibilities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advertisement_responsibilities_id_seq', 1, false);


--
-- TOC entry 3744 (class 0 OID 0)
-- Dependencies: 253
-- Name: advertisements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advertisements_id_seq', 1, false);


--
-- TOC entry 3745 (class 0 OID 0)
-- Dependencies: 243
-- Name: companies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.companies_id_seq', 1, false);


--
-- TOC entry 3746 (class 0 OID 0)
-- Dependencies: 245
-- Name: contract_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contract_types_id_seq', 1, false);


--
-- TOC entry 3747 (class 0 OID 0)
-- Dependencies: 229
-- Name: education_levels_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.education_levels_id_seq', 1, false);


--
-- TOC entry 3748 (class 0 OID 0)
-- Dependencies: 251
-- Name: job_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_types_id_seq', 1, false);


--
-- TOC entry 3749 (class 0 OID 0)
-- Dependencies: 233
-- Name: language_levels_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.language_levels_id_seq', 1, false);


--
-- TOC entry 3750 (class 0 OID 0)
-- Dependencies: 247
-- Name: position_levels_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.position_levels_id_seq', 1, false);


--
-- TOC entry 3751 (class 0 OID 0)
-- Dependencies: 217
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, false);


--
-- TOC entry 3752 (class 0 OID 0)
-- Dependencies: 239
-- Name: user_certificates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_certificates_id_seq', 1, false);


--
-- TOC entry 3753 (class 0 OID 0)
-- Dependencies: 231
-- Name: user_education_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_education_id_seq', 1, false);


--
-- TOC entry 3754 (class 0 OID 0)
-- Dependencies: 227
-- Name: user_experiences_duties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_experiences_duties_id_seq', 1, false);


--
-- TOC entry 3755 (class 0 OID 0)
-- Dependencies: 225
-- Name: user_experiences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_experiences_id_seq', 1, false);


--
-- TOC entry 3756 (class 0 OID 0)
-- Dependencies: 235
-- Name: user_languages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_languages_id_seq', 1, false);


--
-- TOC entry 3757 (class 0 OID 0)
-- Dependencies: 241
-- Name: user_links_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_links_id_seq', 1, false);


--
-- TOC entry 3758 (class 0 OID 0)
-- Dependencies: 237
-- Name: user_skills_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_skills_id_seq', 1, false);


--
-- TOC entry 3759 (class 0 OID 0)
-- Dependencies: 223
-- Name: users_actions_tokens_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_actions_tokens_history_id_seq', 1, false);


--
-- TOC entry 3760 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_actions_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_actions_tokens_id_seq', 1, false);


--
-- TOC entry 3761 (class 0 OID 0)
-- Dependencies: 211
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, false);


--
-- TOC entry 3762 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_roles_id_seq', 5, false);


--
-- TOC entry 3763 (class 0 OID 0)
-- Dependencies: 249
-- Name: working_time_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.working_time_types_id_seq', 1, false);


--
-- TOC entry 3339 (class 2606 OID 75776)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 3342 (class 2606 OID 75778)
-- Name: accounts accounts_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_uuid_key UNIQUE (uuid);


--
-- TOC entry 3334 (class 2606 OID 75754)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 3337 (class 2606 OID 75756)
-- Name: addresses addresses_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_uuid_key UNIQUE (uuid);


--
-- TOC entry 3434 (class 2606 OID 76262)
-- Name: advertisement_categories advertisement_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_categories
    ADD CONSTRAINT advertisement_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3437 (class 2606 OID 76264)
-- Name: advertisement_categories advertisement_categories_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_categories
    ADD CONSTRAINT advertisement_categories_uuid_key UNIQUE (uuid);


--
-- TOC entry 3449 (class 2606 OID 76342)
-- Name: advertisement_opportunities advertisement_opportunities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_opportunities
    ADD CONSTRAINT advertisement_opportunities_pkey PRIMARY KEY (id);


--
-- TOC entry 3452 (class 2606 OID 76344)
-- Name: advertisement_opportunities advertisement_opportunities_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_opportunities
    ADD CONSTRAINT advertisement_opportunities_uuid_key UNIQUE (uuid);


--
-- TOC entry 3444 (class 2606 OID 76317)
-- Name: advertisement_requirements advertisement_requirements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_requirements
    ADD CONSTRAINT advertisement_requirements_pkey PRIMARY KEY (id);


--
-- TOC entry 3447 (class 2606 OID 76319)
-- Name: advertisement_requirements advertisement_requirements_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_requirements
    ADD CONSTRAINT advertisement_requirements_uuid_key UNIQUE (uuid);


--
-- TOC entry 3439 (class 2606 OID 76292)
-- Name: advertisement_responsibilities advertisement_responsibilities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_responsibilities
    ADD CONSTRAINT advertisement_responsibilities_pkey PRIMARY KEY (id);


--
-- TOC entry 3442 (class 2606 OID 76294)
-- Name: advertisement_responsibilities advertisement_responsibilities_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_responsibilities
    ADD CONSTRAINT advertisement_responsibilities_uuid_key UNIQUE (uuid);


--
-- TOC entry 3429 (class 2606 OID 76217)
-- Name: advertisements advertisements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_pkey PRIMARY KEY (id);


--
-- TOC entry 3432 (class 2606 OID 76219)
-- Name: advertisements advertisements_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_uuid_key UNIQUE (uuid);


--
-- TOC entry 3404 (class 2606 OID 76112)
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- TOC entry 3407 (class 2606 OID 76114)
-- Name: companies companies_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_uuid_key UNIQUE (uuid);


--
-- TOC entry 3409 (class 2606 OID 76137)
-- Name: contract_types contract_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract_types
    ADD CONSTRAINT contract_types_pkey PRIMARY KEY (id);


--
-- TOC entry 3412 (class 2606 OID 76139)
-- Name: contract_types contract_types_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract_types
    ADD CONSTRAINT contract_types_uuid_key UNIQUE (uuid);


--
-- TOC entry 3326 (class 2606 OID 75717)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 3369 (class 2606 OID 75931)
-- Name: education_levels education_levels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_levels
    ADD CONSTRAINT education_levels_pkey PRIMARY KEY (id);


--
-- TOC entry 3372 (class 2606 OID 75933)
-- Name: education_levels education_levels_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_levels
    ADD CONSTRAINT education_levels_uuid_key UNIQUE (uuid);


--
-- TOC entry 3424 (class 2606 OID 76197)
-- Name: job_types job_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_types
    ADD CONSTRAINT job_types_pkey PRIMARY KEY (id);


--
-- TOC entry 3427 (class 2606 OID 76199)
-- Name: job_types job_types_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_types
    ADD CONSTRAINT job_types_uuid_key UNIQUE (uuid);


--
-- TOC entry 3379 (class 2606 OID 75983)
-- Name: language_levels language_levels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_levels
    ADD CONSTRAINT language_levels_pkey PRIMARY KEY (id);


--
-- TOC entry 3382 (class 2606 OID 75985)
-- Name: language_levels language_levels_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_levels
    ADD CONSTRAINT language_levels_uuid_key UNIQUE (uuid);


--
-- TOC entry 3414 (class 2606 OID 76157)
-- Name: position_levels position_levels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.position_levels
    ADD CONSTRAINT position_levels_pkey PRIMARY KEY (id);


--
-- TOC entry 3417 (class 2606 OID 76159)
-- Name: position_levels position_levels_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.position_levels
    ADD CONSTRAINT position_levels_uuid_key UNIQUE (uuid);


--
-- TOC entry 3345 (class 2606 OID 75810)
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- TOC entry 3347 (class 2606 OID 75806)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3350 (class 2606 OID 75808)
-- Name: roles roles_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_uuid_key UNIQUE (uuid);


--
-- TOC entry 3394 (class 2606 OID 76058)
-- Name: user_certificates user_certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_certificates
    ADD CONSTRAINT user_certificates_pkey PRIMARY KEY (id);


--
-- TOC entry 3397 (class 2606 OID 76060)
-- Name: user_certificates user_certificates_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_certificates
    ADD CONSTRAINT user_certificates_uuid_key UNIQUE (uuid);


--
-- TOC entry 3374 (class 2606 OID 75953)
-- Name: user_education user_education_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT user_education_pkey PRIMARY KEY (id);


--
-- TOC entry 3377 (class 2606 OID 75955)
-- Name: user_education user_education_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT user_education_uuid_key UNIQUE (uuid);


--
-- TOC entry 3364 (class 2606 OID 75906)
-- Name: user_experiences_duties user_experiences_duties_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences_duties
    ADD CONSTRAINT user_experiences_duties_pkey PRIMARY KEY (id);


--
-- TOC entry 3367 (class 2606 OID 75908)
-- Name: user_experiences_duties user_experiences_duties_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences_duties
    ADD CONSTRAINT user_experiences_duties_uuid_key UNIQUE (uuid);


--
-- TOC entry 3359 (class 2606 OID 75881)
-- Name: user_experiences user_experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences
    ADD CONSTRAINT user_experiences_pkey PRIMARY KEY (id);


--
-- TOC entry 3362 (class 2606 OID 75883)
-- Name: user_experiences user_experiences_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences
    ADD CONSTRAINT user_experiences_uuid_key UNIQUE (uuid);


--
-- TOC entry 3384 (class 2606 OID 76003)
-- Name: user_languages user_languages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_pkey PRIMARY KEY (id);


--
-- TOC entry 3387 (class 2606 OID 76005)
-- Name: user_languages user_languages_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_uuid_key UNIQUE (uuid);


--
-- TOC entry 3399 (class 2606 OID 76085)
-- Name: user_links user_links_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_links
    ADD CONSTRAINT user_links_pkey PRIMARY KEY (id);


--
-- TOC entry 3402 (class 2606 OID 76087)
-- Name: user_links user_links_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_links
    ADD CONSTRAINT user_links_uuid_key UNIQUE (uuid);


--
-- TOC entry 3389 (class 2606 OID 76033)
-- Name: user_skills user_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_pkey PRIMARY KEY (id);


--
-- TOC entry 3392 (class 2606 OID 76035)
-- Name: user_skills user_skills_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_uuid_key UNIQUE (uuid);


--
-- TOC entry 3357 (class 2606 OID 75868)
-- Name: users_actions_tokens_history users_actions_tokens_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_actions_tokens_history
    ADD CONSTRAINT users_actions_tokens_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3354 (class 2606 OID 75855)
-- Name: users_actions_tokens users_actions_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_actions_tokens
    ADD CONSTRAINT users_actions_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3328 (class 2606 OID 75732)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3352 (class 2606 OID 75828)
-- Name: users_roles users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3332 (class 2606 OID 75734)
-- Name: users users_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_uuid_key UNIQUE (uuid);


--
-- TOC entry 3419 (class 2606 OID 76177)
-- Name: working_time_types working_time_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_time_types
    ADD CONSTRAINT working_time_types_pkey PRIMARY KEY (id);


--
-- TOC entry 3422 (class 2606 OID 76179)
-- Name: working_time_types working_time_types_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_time_types
    ADD CONSTRAINT working_time_types_uuid_key UNIQUE (uuid);


--
-- TOC entry 3340 (class 1259 OID 75799)
-- Name: accounts_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX accounts_uuid_idx ON public.accounts USING btree (uuid);


--
-- TOC entry 3335 (class 1259 OID 75767)
-- Name: addresses_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX addresses_uuid_idx ON public.addresses USING btree (uuid);


--
-- TOC entry 3435 (class 1259 OID 76285)
-- Name: advertisement_categories_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX advertisement_categories_uuid_idx ON public.advertisement_categories USING btree (uuid);


--
-- TOC entry 3450 (class 1259 OID 76360)
-- Name: advertisement_opportunities_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX advertisement_opportunities_uuid_idx ON public.advertisement_opportunities USING btree (uuid);


--
-- TOC entry 3445 (class 1259 OID 76335)
-- Name: advertisement_requirements_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX advertisement_requirements_uuid_idx ON public.advertisement_requirements USING btree (uuid);


--
-- TOC entry 3440 (class 1259 OID 76310)
-- Name: advertisement_responsibilities_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX advertisement_responsibilities_uuid_idx ON public.advertisement_responsibilities USING btree (uuid);


--
-- TOC entry 3430 (class 1259 OID 76255)
-- Name: advertisements_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX advertisements_uuid_idx ON public.advertisements USING btree (uuid);


--
-- TOC entry 3405 (class 1259 OID 76130)
-- Name: companies_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX companies_uuid_idx ON public.companies USING btree (uuid);


--
-- TOC entry 3410 (class 1259 OID 76150)
-- Name: contract_types_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX contract_types_uuid_idx ON public.contract_types USING btree (uuid);


--
-- TOC entry 3370 (class 1259 OID 75944)
-- Name: education_levels_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX education_levels_uuid_idx ON public.education_levels USING btree (uuid);


--
-- TOC entry 3425 (class 1259 OID 76210)
-- Name: job_types_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX job_types_uuid_idx ON public.job_types USING btree (uuid);


--
-- TOC entry 3380 (class 1259 OID 75996)
-- Name: language_levels_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX language_levels_uuid_idx ON public.language_levels USING btree (uuid);


--
-- TOC entry 3415 (class 1259 OID 76170)
-- Name: position_levels_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX position_levels_uuid_idx ON public.position_levels USING btree (uuid);


--
-- TOC entry 3343 (class 1259 OID 75821)
-- Name: roles_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX roles_name_idx ON public.roles USING btree (name);


--
-- TOC entry 3348 (class 1259 OID 75822)
-- Name: roles_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX roles_uuid_idx ON public.roles USING btree (uuid);


--
-- TOC entry 3395 (class 1259 OID 76076)
-- Name: user_certificates_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_certificates_uuid_idx ON public.user_certificates USING btree (uuid);


--
-- TOC entry 3375 (class 1259 OID 75976)
-- Name: user_education_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_education_uuid_idx ON public.user_education USING btree (uuid);


--
-- TOC entry 3365 (class 1259 OID 75924)
-- Name: user_experiences_duties_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_experiences_duties_uuid_idx ON public.user_experiences_duties USING btree (uuid);


--
-- TOC entry 3360 (class 1259 OID 75899)
-- Name: user_experiences_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_experiences_uuid_idx ON public.user_experiences USING btree (uuid);


--
-- TOC entry 3385 (class 1259 OID 76026)
-- Name: user_languages_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_languages_uuid_idx ON public.user_languages USING btree (uuid);


--
-- TOC entry 3400 (class 1259 OID 76103)
-- Name: user_links_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_links_uuid_idx ON public.user_links USING btree (uuid);


--
-- TOC entry 3390 (class 1259 OID 76051)
-- Name: user_skills_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_skills_uuid_idx ON public.user_skills USING btree (uuid);


--
-- TOC entry 3355 (class 1259 OID 75861)
-- Name: users_actions_tokens_token_key_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_actions_tokens_token_key_idx ON public.users_actions_tokens USING btree (key);


--
-- TOC entry 3329 (class 1259 OID 75874)
-- Name: users_username_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_username_idx ON public.users USING btree (username) WHERE (status = 1);


--
-- TOC entry 3330 (class 1259 OID 75745)
-- Name: users_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_uuid_idx ON public.users USING btree (uuid);


--
-- TOC entry 3420 (class 1259 OID 76190)
-- Name: working_time_types_uuid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX working_time_types_uuid_idx ON public.working_time_types USING btree (uuid);


--
-- TOC entry 3458 (class 2606 OID 75784)
-- Name: accounts accounts_address_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- TOC entry 3460 (class 2606 OID 75794)
-- Name: accounts accounts_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3457 (class 2606 OID 75779)
-- Name: accounts accounts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3459 (class 2606 OID 75789)
-- Name: accounts accounts_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3455 (class 2606 OID 75757)
-- Name: addresses addresses_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3456 (class 2606 OID 75762)
-- Name: addresses addresses_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3514 (class 2606 OID 76265)
-- Name: advertisement_categories advertisement_categories_advertisement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_categories
    ADD CONSTRAINT advertisement_categories_advertisement_id_fkey FOREIGN KEY (advertisement_id) REFERENCES public.advertisements(id);


--
-- TOC entry 3517 (class 2606 OID 76280)
-- Name: advertisement_categories advertisement_categories_parent_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_categories
    ADD CONSTRAINT advertisement_categories_parent_category_id_fkey FOREIGN KEY (parent_advertisement_category_id) REFERENCES public.advertisement_categories(id);


--
-- TOC entry 3516 (class 2606 OID 76275)
-- Name: advertisement_categories advertisement_categories_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_categories
    ADD CONSTRAINT advertisement_categories_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3515 (class 2606 OID 76270)
-- Name: advertisement_categories advertisement_categories_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_categories
    ADD CONSTRAINT advertisement_categories_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3525 (class 2606 OID 76350)
-- Name: advertisement_opportunities advertisement_opportunities_advertisement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_opportunities
    ADD CONSTRAINT advertisement_opportunities_advertisement_id_fkey FOREIGN KEY (advertisement_id) REFERENCES public.advertisements(id);


--
-- TOC entry 3526 (class 2606 OID 76355)
-- Name: advertisement_opportunities advertisement_opportunities_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_opportunities
    ADD CONSTRAINT advertisement_opportunities_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3524 (class 2606 OID 76345)
-- Name: advertisement_opportunities advertisement_opportunities_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_opportunities
    ADD CONSTRAINT advertisement_opportunities_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3521 (class 2606 OID 76320)
-- Name: advertisement_requirements advertisement_requirements_advertisement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_requirements
    ADD CONSTRAINT advertisement_requirements_advertisement_id_fkey FOREIGN KEY (advertisement_id) REFERENCES public.advertisements(id);


--
-- TOC entry 3522 (class 2606 OID 76325)
-- Name: advertisement_requirements advertisement_requirements_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_requirements
    ADD CONSTRAINT advertisement_requirements_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3523 (class 2606 OID 76330)
-- Name: advertisement_requirements advertisement_requirements_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_requirements
    ADD CONSTRAINT advertisement_requirements_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3519 (class 2606 OID 76300)
-- Name: advertisement_responsibilities advertisement_responsibilities_advertisement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_responsibilities
    ADD CONSTRAINT advertisement_responsibilities_advertisement_id_fkey FOREIGN KEY (advertisement_id) REFERENCES public.advertisements(id);


--
-- TOC entry 3518 (class 2606 OID 76295)
-- Name: advertisement_responsibilities advertisement_responsibilities_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_responsibilities
    ADD CONSTRAINT advertisement_responsibilities_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3520 (class 2606 OID 76305)
-- Name: advertisement_responsibilities advertisement_responsibilities_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisement_responsibilities
    ADD CONSTRAINT advertisement_responsibilities_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3508 (class 2606 OID 76225)
-- Name: advertisements advertisements_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- TOC entry 3513 (class 2606 OID 76250)
-- Name: advertisements advertisements_contract_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_contract_type_id_fkey FOREIGN KEY (contract_type_id) REFERENCES public.contract_types(id);


--
-- TOC entry 3512 (class 2606 OID 76245)
-- Name: advertisements advertisements_job_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_job_type_id_fkey FOREIGN KEY (job_type_id) REFERENCES public.job_types(id);


--
-- TOC entry 3509 (class 2606 OID 76230)
-- Name: advertisements advertisements_position_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_position_level_id_fkey FOREIGN KEY (position_level_id) REFERENCES public.position_levels(id);


--
-- TOC entry 3511 (class 2606 OID 76240)
-- Name: advertisements advertisements_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3507 (class 2606 OID 76220)
-- Name: advertisements advertisements_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3510 (class 2606 OID 76235)
-- Name: advertisements advertisements_working_time_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_working_time_type_id_fkey FOREIGN KEY (working_time_type_id) REFERENCES public.working_time_types(id);


--
-- TOC entry 3498 (class 2606 OID 76125)
-- Name: companies companies_address_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- TOC entry 3496 (class 2606 OID 76115)
-- Name: companies companies_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3497 (class 2606 OID 76120)
-- Name: companies companies_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3499 (class 2606 OID 76140)
-- Name: contract_types contract_types_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract_types
    ADD CONSTRAINT contract_types_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3500 (class 2606 OID 76145)
-- Name: contract_types contract_types_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract_types
    ADD CONSTRAINT contract_types_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3475 (class 2606 OID 75934)
-- Name: education_levels education_levels_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_levels
    ADD CONSTRAINT education_levels_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3476 (class 2606 OID 75939)
-- Name: education_levels education_levels_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_levels
    ADD CONSTRAINT education_levels_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3506 (class 2606 OID 76205)
-- Name: job_types job_types_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_types
    ADD CONSTRAINT job_types_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3505 (class 2606 OID 76200)
-- Name: job_types job_types_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_types
    ADD CONSTRAINT job_types_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3481 (class 2606 OID 75986)
-- Name: language_levels language_levels_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_levels
    ADD CONSTRAINT language_levels_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3482 (class 2606 OID 75991)
-- Name: language_levels language_levels_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_levels
    ADD CONSTRAINT language_levels_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3502 (class 2606 OID 76165)
-- Name: position_levels position_levels_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.position_levels
    ADD CONSTRAINT position_levels_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3501 (class 2606 OID 76160)
-- Name: position_levels position_levels_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.position_levels
    ADD CONSTRAINT position_levels_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3462 (class 2606 OID 75816)
-- Name: roles roles_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3461 (class 2606 OID 75811)
-- Name: roles roles_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3491 (class 2606 OID 76066)
-- Name: user_certificates user_certificates_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_certificates
    ADD CONSTRAINT user_certificates_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3492 (class 2606 OID 76071)
-- Name: user_certificates user_certificates_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_certificates
    ADD CONSTRAINT user_certificates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3490 (class 2606 OID 76061)
-- Name: user_certificates user_certificates_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_certificates
    ADD CONSTRAINT user_certificates_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3479 (class 2606 OID 75966)
-- Name: user_education user_education_education_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT user_education_education_level_id_fkey FOREIGN KEY (education_level_id) REFERENCES public.education_levels(id);


--
-- TOC entry 3477 (class 2606 OID 75956)
-- Name: user_education user_education_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT user_education_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3478 (class 2606 OID 75961)
-- Name: user_education user_education_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT user_education_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3480 (class 2606 OID 75971)
-- Name: user_education user_education_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT user_education_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3474 (class 2606 OID 75919)
-- Name: user_experiences_duties user_experiences_duties_user_experience_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences_duties
    ADD CONSTRAINT user_experiences_duties_user_experience_id_fkey FOREIGN KEY (user_experience_id) REFERENCES public.user_experiences(id);


--
-- TOC entry 3473 (class 2606 OID 75914)
-- Name: user_experiences_duties user_experiences_duties_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences_duties
    ADD CONSTRAINT user_experiences_duties_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3472 (class 2606 OID 75909)
-- Name: user_experiences_duties user_experiences_duties_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences_duties
    ADD CONSTRAINT user_experiences_duties_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3469 (class 2606 OID 75884)
-- Name: user_experiences user_experiences_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences
    ADD CONSTRAINT user_experiences_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3470 (class 2606 OID 75889)
-- Name: user_experiences user_experiences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences
    ADD CONSTRAINT user_experiences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3471 (class 2606 OID 75894)
-- Name: user_experiences user_experiences_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experiences
    ADD CONSTRAINT user_experiences_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3485 (class 2606 OID 76016)
-- Name: user_languages user_languages_language_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_language_level_id_fkey FOREIGN KEY (language_level_id) REFERENCES public.language_levels(id);


--
-- TOC entry 3486 (class 2606 OID 76021)
-- Name: user_languages user_languages_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3483 (class 2606 OID 76006)
-- Name: user_languages user_languages_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3484 (class 2606 OID 76011)
-- Name: user_languages user_languages_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3493 (class 2606 OID 76088)
-- Name: user_links user_links_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_links
    ADD CONSTRAINT user_links_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3494 (class 2606 OID 76093)
-- Name: user_links user_links_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_links
    ADD CONSTRAINT user_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3495 (class 2606 OID 76098)
-- Name: user_links user_links_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_links
    ADD CONSTRAINT user_links_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3487 (class 2606 OID 76036)
-- Name: user_skills user_skills_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3488 (class 2606 OID 76041)
-- Name: user_skills user_skills_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3489 (class 2606 OID 76046)
-- Name: user_skills user_skills_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3468 (class 2606 OID 75869)
-- Name: users_actions_tokens_history users_actions_tokens_history_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_actions_tokens_history
    ADD CONSTRAINT users_actions_tokens_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3467 (class 2606 OID 75856)
-- Name: users_actions_tokens users_actions_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_actions_tokens
    ADD CONSTRAINT users_actions_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3465 (class 2606 OID 75839)
-- Name: users_roles users_roles_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 3464 (class 2606 OID 75834)
-- Name: users_roles users_roles_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3463 (class 2606 OID 75829)
-- Name: users_roles users_roles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3466 (class 2606 OID 75844)
-- Name: users_roles users_roles_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3453 (class 2606 OID 75735)
-- Name: users users_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3454 (class 2606 OID 75740)
-- Name: users users_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3503 (class 2606 OID 76180)
-- Name: working_time_types working_time_types_user_id_created_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_time_types
    ADD CONSTRAINT working_time_types_user_id_created_fkey FOREIGN KEY (user_id_created) REFERENCES public.users(id);


--
-- TOC entry 3504 (class 2606 OID 76185)
-- Name: working_time_types working_time_types_user_id_last_modified_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.working_time_types
    ADD CONSTRAINT working_time_types_user_id_last_modified_fkey FOREIGN KEY (user_id_last_modified) REFERENCES public.users(id);


--
-- TOC entry 3729 (class 0 OID 0)
-- Dependencies: 218
-- Name: TABLE roles; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,UPDATE ON TABLE public.roles TO user_role;


--
-- TOC entry 3734 (class 0 OID 0)
-- Dependencies: 212
-- Name: TABLE users; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,UPDATE ON TABLE public.users TO user_role;


--
-- TOC entry 3735 (class 0 OID 0)
-- Dependencies: 222
-- Name: TABLE users_actions_tokens; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.users_actions_tokens TO user_role;


--
-- TOC entry 3736 (class 0 OID 0)
-- Dependencies: 224
-- Name: TABLE users_actions_tokens_history; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,UPDATE ON TABLE public.users_actions_tokens_history TO user_role;


--
-- TOC entry 3737 (class 0 OID 0)
-- Dependencies: 220
-- Name: TABLE users_roles; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,UPDATE ON TABLE public.users_roles TO user_role;


-- Completed on 2023-11-05 15:16:55

--
-- PostgreSQL database dump complete
--

